/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ioc.dam.m13.tutorfinder.desktop;

import ioc.dam.m13.tutorfinder.client.TFClient;
import ioc.dam.m13.tutorfinder.client.TFClientImple;
import ioc.dam.m13.tutorfinder.dtos.UserDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre
 */
public class login extends javax.swing.JFrame {

    int intents = 0;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Al initComponents tenim els titols i botons de la part del Login
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jOptionPane1 = new javax.swing.JOptionPane();
        labelTitol = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        textUser = new javax.swing.JTextField();
        buttonRegistrar = new javax.swing.JButton();
        buttonSortir = new javax.swing.JButton();
        buttonIniciar = new javax.swing.JButton();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelTitol.setFont(new java.awt.Font("Gigi", 0, 105)); // NOI18N
        labelTitol.setText("TutorFinder");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = -70;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(270, 380, 0, 0);
        getContentPane().add(labelTitol, gridBagConstraints);

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelUser.setText("USUARI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 400, 0, 0);
        getContentPane().add(labelUser, gridBagConstraints);

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPassword.setText("CONTRASENYA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 400, 0, 0);
        getContentPane().add(labelPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 276;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(textPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 276;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(textUser, gridBagConstraints);

        buttonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonRegistrar.setText("REGISTRAR-SE GRATIS");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = -35;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 80, 0, 0);
        getContentPane().add(buttonRegistrar, gridBagConstraints);

        buttonSortir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonSortir.setText("SORTIR");
        buttonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        getContentPane().add(buttonSortir, gridBagConstraints);

        buttonIniciar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonIniciar.setText("INICIAR SESSIÓ");
        buttonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        getContentPane().add(buttonIniciar, gridBagConstraints);

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ioc/dam/m13/tutorfinder/desktop/fondo.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(fons, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Fem que en el moment de premer el botó sortir es tanqui l'aplicació
     *
     */

    private void buttonSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSortirActionPerformed

    /**
     * Botó que valida si es correcte el usuari i contrasenya per iniciar
     * sessió.
     *
     */
    private void buttonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciarActionPerformed
        // TODO add your handling code here:
        
        //Fem la connexió amb la classe que es connecta amb el servidor
        TFClient l = new TFClientImple();
        // comprovem que ens retorni tru o false amb el usuari i contrasenya


        char clave[]=textPassword.getPassword();

        String clavedef=new String(clave);
        //Mostre usuari i contrasenya
        String usuari = textUser.getText();
        boolean res = l.login(usuari,clavedef);

        System.out.println("USUARI: " + usuari);
        System.out.println("CONTRASENYA: " + clavedef);

        System.out.println("AQUI SI QUE LLEGO ");
        //Fem les comprovacions si ens retorna true i l'usuari es admin. admin ara mateix es com si 
        //fos el rol, això s'ha de acabar de polir.
        if(res==true){
            menuPrincipalAdmin formMenu;
            //instanciem un objecte UserDTO que es on ens torna 
            //tota la informació el metode userData del TFClientImple
            UserDTO userData = l.userData(usuari);
            
            //Del userData saquem el role que es un String i pot ser
            //"admin", "tutor", "student"
            String userRole = userData.getUserRole();
            
            switch (userRole){
                case "admin" :
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Benvingut Administrador!!\n"
                        + "Acabes d'entrar al sistema correctament", "Missatge de benvinguda",
                        JOptionPane.INFORMATION_MESSAGE);
                    formMenu = new menuPrincipalAdmin();
                    formMenu.setVisible(true);
                    break;
                    
                case "tutor" :
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Benvingut Administrador!!\n"
                        + "Acabes d'entrar al sistema correctament", "Missatge de benvinguda",
                        JOptionPane.INFORMATION_MESSAGE);
                    formMenu = new menuPrincipalAdmin();
                    formMenu.setVisible(true);
                    break;
                    
                case "student" :
                    System.out.println("AQUI SI QUE LLEGO 3333");
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Benvingut Administrador!!\n"
                        + "Acabes d'entrar al sistema correctament", "Missatge de benvinguda",
                        JOptionPane.INFORMATION_MESSAGE);
                    formMenu = new menuPrincipalAdmin();
                    formMenu.setVisible(true);
                    break;
                    
            }
            
            /*
            System.out.println("AQUI SI QUE LLEGOoooooooooo ");
            System.out.println("Uusuari i contrasenya correctes"+ res);
            
            if(usuari.equals("admin")){
                this.dispose();
                JOptionPane.showMessageDialog(null, "Benvingut Administrador!!\n"
                    + "Acabes d'entrar al sistema correctament", "Missatge de benvinguda",
                    JOptionPane.INFORMATION_MESSAGE);
                menuPrincipalAdmin formMenu = new menuPrincipalAdmin();
                formMenu.setVisible(true);
            }
            
            if(res==true){
                
                System.out.println("Uusuari i contrasenya correctes"+ res);
                
                if(usuari.equals("client")){
                    System.out.println("AQUI SI QUE LLEGO 3333");
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Benvingut Administrador!!\n"
                        + "Acabes d'entrar al sistema correctament", "Missatge de benvinguda",
                        JOptionPane.INFORMATION_MESSAGE);
                    menuPrincipalAdmin formMenu = new menuPrincipalAdmin();
                    formMenu.setVisible(true);
                }
            }
            
            if(res==true){
                System.out.println("Uusuari i contrasenya correctes"+ res);
                
                if(usuari.equals("professor")){
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Benvingut Administrador!!\n"
                        + "Acabes d'entrar al sistema correctament", "Missatge de benvinguda",
                        JOptionPane.INFORMATION_MESSAGE);
                    menuPrincipalAdmin formMenu = new menuPrincipalAdmin();
                    formMenu.setVisible(true);
                }
            }
            */
        }
        
        //si es false el usuari i contrasenya mostra error      
        if(res==false){                  
            System.out.println("Uusuari i contrasenya INCORRECTE "+ res);
            JOptionPane.showMessageDialog(null, "Acces denegat !!\n"
            + "Si us plau introduieix l'usuari o contrasenya correctes", "Acces denegat",
            JOptionPane.ERROR_MESSAGE);

            intents++;
        }
        //controlem els intents i si son 3 tanquem l'aplicació per superar intents
        if (intents > 2) {
            JOptionPane.showMessageDialog(null, "Acces Bloquejat ha superat el maxim d'intents erronis!!");
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_buttonIniciarActionPerformed
    /**
     * Botó que ens fa anar a la pantalla de crear usuari nou.
     *
     */

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:

        registrar formRegistrar = new registrar();

        formRegistrar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_buttonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIniciar;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JButton buttonSortir;
    private javax.swing.JLabel fons;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
